name: deploy-k8s
on:
  push:
      branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # get pod list
    - uses: actions/checkout@master
    - name: deploy to cluster
      uses: coderYii/kubectl@v2.0.0-y
      with: # defaults to latest kubectl binary version
        kubeHosts: ${{ secrets.KUBE_HOSTS_CONFIG}}
        config: ${{ secrets.KUBE_CONFIG_DATA }}
        version: v1.21.4
        command: get pod
