name: deploy-k8s
on:
  push:
      branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # 让K8s应用deployment
    - uses: actions/checkout@v2
    - run: |
        sudo echo '82.156.192.56 yii.k8s' | sudo tee -a /etc/hosts
    - name: Trigger deploy
      uses: Consensys/kubernetes-action@master
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
      with:
        args: version
