name: deploy-k8s
on:
  push:
      branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # 让K8s应用deployment
    - uses: actions/checkout@master
    - run: |
        sudo echo '82.156.192.56 yii.k8s' | sudo tee -a /etc/hosts
    - name: deploy to cluster
      uses: steebchen/kubectl@v2.0.0
      with: # defaults to latest kubectl binary version
        config: ${{ secrets.KUBE_CONFIG_DATA }}
        version: v1.21.4
        command: version
